export enum HelpTypes {
  BEST_MOVES = 1,
  BEST_MOVES_ENEMY = 2,
  SELECT_BEST_MOVES = 3,
  SELECT_BEST_MOVES_ENEMY = 4,
  PRED_WINNER = 5,
  PRED_SUPERIOR = 6,
  HEATMAP_FULL = 13,
  HEATMAP_ZONE = 17,
  HEATMAP_ZONE_ENEMY = 18,
  HEATMAP_ZONE_QUARTER = 23,
  HEATMAP_ZONE_2_QUARTERS = 33,
}
