export enum HintTypes {
  GET_HINT_BEST_MOVES = 'GET_HINT_BEST_MOVES',
  GET_HINT_BEST_MOVES_ENEMY = 'GET_HINT_BEST_MOVES_ENEMY',
  GET_HINT_SHOW_BEST = 'GET_HINT_SHOW_BEST',
  GET_HINT_SHOW_BEST_ENEMY = 'GET_HINT_SHOW_BEST_ENEMY',
  GET_HINT_SHOW_SUPERIOR = 'GET_HINT_SHOW_SUPERIOR',
  GET_HINT_HEATMAP_FULL = 'GET_HINT_HEATMAP_FULL',
  GET_HINT_HEATMAP = 'GET_HINT_HEATMAP',
  GET_HINT_HEATMAP_ZONE = 'GET_HINT_HEATMAP_ZONE',
  GET_HINT_HEATMAP_ZONE_ENEMY = 'GET_HINT_HEATMAP_ZONE_ENEMY',
  GET_HINT_HEATMAP_ZONE_QUARTER = 'GET_HINT_HEATMAP_ZONE_QUARTER',
  GET_HINT_HEATMAP_ZONE_2_QUARTERS = 'GET_HINT_HEATMAP_ZONE_2_QUARTERS',
}
